# Generated by Django 5.2.12 on 2026-03-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_access',
            field=models.BooleanField(default=False, verbose_name='Есть доступ к платному контенту'),
        ),
    ]
