# Generated by Django 5.2 on 2026-03-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile_has_access"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "Профиль", "verbose_name_plural": "Профили"},
        ),
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[("student", "Студент"), ("teacher", "Преподаватель")],
                default="student",
                max_length=10,
                verbose_name="Роль",
            ),
        ),
    ]
