"""
Django settings for settings project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Загружаем переменные из .env (для GEMINI_API_KEY, DJANGO_SECRET_KEY и т.д.)
from dotenv import load_dotenv
load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY: в продакшене задать переменную окружения DJANGO_SECRET_KEY
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-3k*m=rh()s-8_z9sdrw@=&-8zwoa$y_om7)+64quza=yk#ouyk",
)

# SECURITY: в продакшене задать DJANGO_DEBUG=0 или False
DEBUG = os.environ.get("DJANGO_DEBUG", "True").lower() in ("true", "1", "yes")

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
if os.environ.get("RENDER_EXTERNAL_HOSTNAME"):
    ALLOWED_HOSTS.append(os.environ["RENDER_EXTERNAL_HOSTNAME"])


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "cloudinary",
    "cloudinary_storage",
    "main",
    "users",
    "courses",
    "markdownx",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "settings.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "users.context_processors.user_role",
                "main.context_processors.ga4",
            ],
        },
    },
]

WSGI_APPLICATION = "settings.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
if os.environ.get("DATABASE_URL"):
    import dj_database_url
    DATABASES = {"default": dj_database_url.config(default=os.environ["DATABASE_URL"], conn_max_age=600)}
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# По умолчанию — русский; гость с «/» попадает на /ru/, дальше язык выбирает переключатель.
LANGUAGE_CODE = "ru"

LANGUAGES = [
    ("ru", "Русский"),
    ("en", "English"),
    ("it", "Italiano"),
]

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

LOCALE_PATHS = [
    BASE_DIR / "locale",
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [Path(BASE_DIR, "static/")]

# Медиа-файлы (аватары, картинки уроков).
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Загрузки: дефолт Django ~2.5 МБ в памяти; крупные multipart уходят на диск, но лимит тела запроса
# может давать RequestDataTooBig при больших файлах без этих значений.
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024

# Cloudinary на проде (Render): без CLOUDINARY_URL запись в media/ на эфемерном диске часто даёт 500.
CLOUDINARY_URL = os.environ.get("CLOUDINARY_URL", "").strip()
# Django 5.2: при задании STORAGES обязательны и default, и staticfiles (иначе collectstatic падает на Render).
_WHITENOISE_STATICFILES = {
    "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
}
if CLOUDINARY_URL:
    STORAGES = {
        "default": {
            "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
        },
        "staticfiles": _WHITENOISE_STATICFILES,
    }
else:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": _WHITENOISE_STATICFILES,
    }

# Куда перенаправлять после входа/выхода
LOGIN_REDIRECT_URL = "index"
LOGOUT_REDIRECT_URL = "index"
LOGIN_URL = "users:login"

# AI-помощник на странице урока
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "")
GROQ_API_KEY = os.environ.get("GROQ_API_KEY", "")

# Stripe (оплата доступа)
STRIPE_SECRET_KEY = os.environ.get("STRIPE_SECRET_KEY", "")
STRIPE_PUBLISHABLE_KEY = os.environ.get("STRIPE_PUBLISHABLE_KEY", "")
STRIPE_PRICE_ID = os.environ.get("STRIPE_PRICE_ID", "")
STRIPE_WEBHOOK_SECRET = os.environ.get("STRIPE_WEBHOOK_SECRET", "")
# Единая цена полного доступа к обоим курсам (USD). В Stripe Product/Price должна быть та же сумма.
BUNDLE_PRICE_USD = int(os.environ.get("BUNDLE_PRICE_USD", "4"))

# True — все залогиненные пользователи видят весь контент без оплаты (публичный портфолио-сайт).
# На Render для бесплатного сайта задайте FREE_PUBLIC_ACCESS=True (или не задавайте — по умолчанию True).
# False — платный режим (Stripe). Для демо оплаты локально: FREE_PUBLIC_ACCESS=False + тестовые ключи Stripe.
FREE_PUBLIC_ACCESS = os.environ.get("FREE_PUBLIC_ACCESS", "True").lower() in (
    "true",
    "1",
    "yes",
)

# Google Analytics 4: идентификатор потока вида G-XXXXXXXXXX (Admin → Data streams → Web).
# Пусто — gtag не подключается (удобно для локальной разработки).
GA4_MEASUREMENT_ID = os.environ.get("GA4_MEASUREMENT_ID", "").strip()

# Продакшен за HTTPS-прокси (Render и т.п.): иначе request.is_secure() часто False → CSRF 403 на POST
# (в т.ч. django-markdownx «markdownify» в админке).
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    USE_X_FORWARDED_HOST = True

_csrf_origins = []
_render_host = os.environ.get("RENDER_EXTERNAL_HOSTNAME", "").strip()
if _render_host:
    _csrf_origins.append(f"https://{_render_host}")
if not DEBUG:
    _local_hosts = {"localhost", "127.0.0.1", "[::1]"}
    for _h in ALLOWED_HOSTS:
        _hn = (_h or "").strip()
        if _hn and _hn not in _local_hosts:
            _csrf_origins.append(f"https://{_hn}")
_csrf_origins = list(dict.fromkeys(_csrf_origins))
_extra_csrf = os.environ.get("CSRF_TRUSTED_ORIGINS", "").strip()
if _extra_csrf:
    for _o in _extra_csrf.split(","):
        _o = _o.strip()
        if _o:
            _csrf_origins.append(_o)
    _csrf_origins = list(dict.fromkeys(_csrf_origins))
if _csrf_origins:
    CSRF_TRUSTED_ORIGINS = _csrf_origins

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
