# Generated by Django 5.2.12 on 2026-03-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_book_title_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Опубликован'),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('junior', 'Python для начинающих'), ('pro', 'Python для профессионалов')], default='junior', max_length=20, verbose_name='Уровень'),
        ),
    ]
