# Generated by Django 5.2.12 on 2026-03-12 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lessonaimessage'),
        ('courses', '0006_course_is_active_course_level'),
    ]

    operations = [
    ]
