# Generated by Django 5.2 on 2026-03-16 16:05

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_course_cover_image_lesson_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="content",
            field=markdownx.models.MarkdownxField(
                blank=True, verbose_name="Содержание"
            ),
        ),
    ]
