# Generated by Django 5.2 on 2026-03-20 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0010_coursecertificate"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Grade",
        ),
    ]
