# Generated by Django 5.2 on 2026-03-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0012_add_course_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="author_image",
            field=models.ImageField(
                blank=True,
                help_text="Показывается в финальном уроке Pro под заголовком «Слово автора», если загружено.",
                null=True,
                upload_to="courses/authors/",
                verbose_name="Фото автора (блок «Слово автора»)",
            ),
        ),
    ]
