# Generated by Django 5.2 on 2026-03-26 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0013_course_author_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={
                "ordering": ["order"],
                "verbose_name": "Книга",
                "verbose_name_plural": "Книги",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.AlterModelOptions(
            name="coursecertificate",
            options={
                "ordering": ["-issued_at"],
                "verbose_name": "Сертификат курса",
                "verbose_name_plural": "Сертификаты курсов",
            },
        ),
        migrations.AlterModelOptions(
            name="coursereview",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Отзыв о курсе",
                "verbose_name_plural": "Отзывы о курсах",
            },
        ),
        migrations.AlterModelOptions(
            name="enrollment",
            options={
                "verbose_name": "Запись на курс",
                "verbose_name_plural": "Записи на курсы",
            },
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ["order"],
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
        migrations.AlterModelOptions(
            name="lessonaimessage",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Сообщение ИИ по уроку",
                "verbose_name_plural": "Сообщения ИИ по урокам",
            },
        ),
        migrations.AlterModelOptions(
            name="lessonprogress",
            options={
                "verbose_name": "Прогресс урока",
                "verbose_name_plural": "Прогресс уроков",
            },
        ),
        migrations.AlterField(
            model_name="lessonaimessage",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_messages",
                to="courses.lesson",
                verbose_name="Урок",
            ),
        ),
        migrations.AlterField(
            model_name="lessonaimessage",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_ai_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="lessonprogress",
            name="completed_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата прохождения"),
        ),
        migrations.AlterField(
            model_name="lessonprogress",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress",
                to="courses.lesson",
                verbose_name="Урок",
            ),
        ),
        migrations.AlterField(
            model_name="lessonprogress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_progress",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
