# Generated by Django 5.2.12 on 2026-04-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0015_remove_coursecertificate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="author_image",
            field=models.ImageField(
                blank=True,
                help_text="Показывается в финальном уроке Pro у маркера <!-- AUTHOR_PHOTO -->. Если не задано — можно использовать «Картинку урока» в том же уроке.",
                null=True,
                upload_to="courses/authors/",
                verbose_name="Фото автора (блок «Слово автора»)",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Обычно — иллюстрация сверху урока. В финальном уроке Pro, если в курсе не задано «Фото автора», эта картинка подставляется в «Слово автора» (маркер <!-- AUTHOR_PHOTO -->), без дубля сверху страницы.",
                null=True,
                upload_to="courses/lessons/",
                verbose_name="Картинка урока",
            ),
        ),
    ]
