# Generated by Django 5.2.12 on 2026-04-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0016_lesson_image_author_fallback_help"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="Каталог и страница курса. Если пусто — берётся «Картинка урока» у первого урока (по порядку).",
                null=True,
                upload_to="courses/covers/",
                verbose_name="Обложка курса",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="У первого урока при пустой обложке курса — может быть обложкой в каталоге. Обычно — иллюстрация сверху урока (если у курса уже есть обложка). В финальном уроке Pro без «Фото автора» у курса — блок «Слово автора» (<!-- AUTHOR_PHOTO -->), без дубля сверху.",
                null=True,
                upload_to="courses/lessons/",
                verbose_name="Картинка урока",
            ),
        ),
    ]
