# Generated by Django 5.2.12 on 2026-04-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0017_course_cover_fallback_help"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="Каталог и страница курса. Если пусто — берётся «Картинка урока»: у junior — со второго урока (первый часто слишком большой для сохранения в админке), у pro — с первого.",
                null=True,
                upload_to="courses/covers/",
                verbose_name="Обложка курса",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Junior: у второго урока при пустой обложке курса — может быть обложкой в каталоге. Pro: у первого урока. Иначе — иллюстрация сверху урока (если урок не источник обложки). Финальный урок Pro без «Фото автора» у курса — «Слово автора» (<!-- AUTHOR_PHOTO -->).",
                null=True,
                upload_to="courses/lessons/",
                verbose_name="Картинка урока",
            ),
        ),
    ]
