# Generated by Django 5.2.12 on 2026-04-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0018_junior_cover_from_second_lesson"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="Каталог и страница курса. Если пусто — берётся «Картинка урока»: у junior — со второго урока; у pro — с третьего (финальный урок с «Слово автора» не трогаем).",
                null=True,
                upload_to="courses/covers/",
                verbose_name="Обложка курса",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Junior: второй урок — запасная обложка курса. Pro: третий урок — обложка; шестой — отдельно «Слово автора» (<!-- AUTHOR_PHOTO -->). Иначе иллюстрация сверху, если урок не источник обложки.",
                null=True,
                upload_to="courses/lessons/",
                verbose_name="Картинка урока",
            ),
        ),
    ]
