# Generated by Django 5.2.12 on 2026-04-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0019_pro_cover_from_third_lesson"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="Каталог и страница курса. Если пусто — «Картинка урока»: junior — 2-й по списку; pro — у урока с полем «Порядок» = 3 (финальный урок с «Слово автора» — отдельно).",
                null=True,
                upload_to="courses/covers/",
                verbose_name="Обложка курса",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Junior: 2-й урок — запасная обложка. Pro: урок с «Порядок» 3 — обложка; финальный урок — «Слово автора» (<!-- AUTHOR_PHOTO -->). Иначе иллюстрация сверху, если урок не источник обложки.",
                null=True,
                upload_to="courses/lessons/",
                verbose_name="Картинка урока",
            ),
        ),
    ]
