"""Generate courses/i18n_junior_lessons.py with gettext() for each prose line (for makemessages)."""
import pathlib

root = pathlib.Path(__file__).resolve().parents[1]
lines_path = root / "scripts" / "prose_lines_utf8.txt"
out_path = root / "courses" / "i18n_junior_lessons.py"

raw = lines_path.read_text(encoding="utf-8").splitlines()
lines = [ln for ln in raw if ln.strip()]

parts = [
    '"""',
    "Catalog of Junior lesson strings for gettext (auto-generated by scripts/gen_junior_i18n_py.py).",
    "Run: python manage.py makemessages -l it -l en",
    '"""',
    "from django.utils.translation import gettext_lazy as _",
    "",
    "def _register_junior_lesson_strings():",
    "    \"\"\"Side effect: strings registered for xgettext.\"\"\"",
]

for s in lines:
    parts.append(f"    _({repr(s)})")

parts.append("")
parts.append("")
out_path.write_text("\n".join(parts), encoding="utf-8")
print("Wrote", len(lines), "strings to", out_path)
